include rose-pine-moon.conf

# BEGIN_KITTY_THEME
# Rosé Pine Moon
include current-theme.conf
# END_KITTY_THEME

#########################
###### KEYBINDINGS ######
#########################
kitty_mod alt
map kitty_mod+q close_tab
map kitty_mod+t new_tab


#########################
######## CONFIG #########
#########################
confirm_os_window_close 0